openapi: 3.0.3
servers:
- url: http://localhost:2082/
  description: url Local
- url: https://dev.nttdata.com/mspromotion/
  description: url Desarrollo
- url: https://nttdata.com/mspromotion/
  description: url Produccion